# Shared project metadata. These values are identical for every Minecraft version.
mod.id=flashbackexportextras
mod.archive_name=flashbackexportextras
mod.name=Flashback Export Extras
mod.group=com.rethinkqaq
mod.version=1.1.2-dev

# Gradle options.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
org.gradle.configuration-cache=true
